export const firms = { '38': 'Fortune 500 Service Company',
  '49': 'Fortune 100 CPG Company',
  '55': 'Multibillion-dollar Telecommunications Company',
  '57': 'Fortune 500 Wine &amp; Spirits Company',
  '58': 'Leading Private Equity Firm',
  '59': 'Investment Management Firm',
  '61': 'Leading Financial Services Company',
  '62': 'Multibillion-dollar Insurance Carrier',
  '66': 'PE-owned Portfolio Company',
  '68': 'Fast-Growing Technology Company',
  '71': 'Multibillion-dollar CPG Company',
  '73': 'Multibillion-dollar Private Technology / Telecommunications Company',
  '81': 'Not-for-Profit Technology Company',
  '93': 'Multibillion-Dollar Online Retail Company',
  '94': 'Multibillion-dollar Technology Protection Company',
  '104': 'Government Nonprofit for Economic Development',
  '105': 'Not-for-Profit Insurance Company',
  '107': 'Fortune 100 Health Insurance Company',
  '112': 'Multinational Consumer Packaged Goods Company',
  '114': 'Multibillion-dollar Chemicals Company',
  '116': 'Fortune 50 Consumer Goods Company',
  '119': 'Private Equity Firm',
  '120': '$6B Manufacturing Company',
  '121': 'Multibillion-dollar Software and Processing Solutions Company',
  '127': 'Data Systems Company',
  '129': 'Fortune 100 Aerospace and Defense Company',
  '132': 'Multibillion-dollar Beauty Retail Company',
  '133': 'Specialist Insurer',
  '136': 'Information Services Company',
  '137': 'Multibillion-dollar Software Company',
  '138': 'Fortune 100 Pharmaceutical Company',
  '139': 'Fortune 150 Industrial Manufacturing Company',
  '141': 'Leading Financial Advising Firm',
  '144': 'Fortune 150 CPG Company',
  '145': 'Leading Financial Firm',
  '148': 'Multibillion-dollar Conglomerate',
  '150': 'Multimillion-dollar Oil &amp; Gas Company',
  '151': '$2B Food Services Company',
  '152': '$10 billion Health Maintenance &amp; Health Insurance Company',
  '157': 'Multibillion-dollar Private Software and Technology Services Company',
  '164': 'Education Technology Solutions Company',
  '165': 'Multibillion-dollar Health Maintenance &amp; Health Insurance Company',
  '168': 'Multibillion-dollar Automotive Company',
  '226': 'Leading Entertainment Services Company',
  '227': 'Multimillion-dollar Specialty Chemical Manufacturer',
  '229': 'Multibillion-dollar Transportation Services Company',
  '232': 'Fortune 300 CPG Company',
  '235': 'Fortune 50 Conglomerate',
  '236': 'Fortune 100 Online Retail Company',
  '238': 'PE-owned Medical Device Manufacturer',
  '239': 'Multibillion-dollar Healthcare Manufacturer',
  '240': 'Fortune 100 Healthcare Company',
  '245': 'Fortune 100 Healthcare Services and Distribution Company',
  '248': 'Multimillion-dollar Industrial Manufacturing Company',
  '250': 'Fortune 100 Retail Company',
  '251': 'Australia Post',
  '255': 'Private Investment Firm',
  '257': 'Leading Global Financial Services Provider',
  '261': 'Multibillion-Dollar Retail Company',
  '268': 'Mattel Consumer Products',
  '270': 'SC Johnson',
  '271': 'Avon',
  '272': 'Beazley plc',
  '273': 'KKR',
  '274': 'New York Needs You',
  '275': 'Aetna Inc.',
  '276': 'LAN Airlines',
  '277': 'SteelSeries',
  '278': 'Asurion, LLC',
  '279': 'Charles River Associates (CRA)',
  '280': 'Smarterville, Inc.',
  '282': 'Limelight Networks, Inc.',
  '283': 'Cerberus Capital Management',
  '287': 'Sterling Partners Portfolio Company',
  '292': 'SunTrust Banks, Inc.',
  '294': 'McKesson Corporation',
  '295': 'Promethean, Inc.',
  '303': 'Limelight Networks, Inc.',
  '304': 'Inchcape plc.',
  '309': 'Multimillion-dollar Private Healthcare Software Company',
  '311': 'SunGard Availability Services',
  '313': 'diva, BBRC Retail',
  '315': 'Fortune 100 Consumer Organization',
  '317': 'General Electric Company',
  '320': 'Multibillion-dollar Health Services Company',
  '322': 'Pernod Ricard SA',
  '325': 'Consumer Technology Company',
  '331': 'Golden Gate Capital',
  '333': 'Fortune 500 Retail Company',
  '595': 'Yum! Brands',
  '597': 'Vitera Healthcare Solutions',
  '598': 'Estée Lauder Companies',
  '601': 'DocuSign',
  '602': 'Inc.',
  '610': 'LABVANTAGE Solutions',
  '611': 'LABVANTAGE Solutions Inc.',
  '612': 'inBloom',
  '613': 'inBloom Inc.',
  '615': 'Fast-growing Technology Solutions Company',
  '623': 'HubSpot',
  '624': 'Lenovo Latin America',
  '627': 'OANDA',
  '628': 'Consulting Branch of a Leading Private Equity Firm',
  '631': 'Top Private Equity Firm',
  '634': 'Multibillion-dollar Technology/Insurance Company',
  '636': 'Fortune 50 Healthcare/Retail Company',
  '641': 'Jaguar Land Rover Automotive',
  '644': 'Coverys',
  '645': 'Ferrara Candy Company',
  '647': 'Uline',
  '650': 'Urban Compass',
  '659': 'Multibillion-dollar Consumer Products Company',
  '662': 'Voxy',
  '664': 'Fortune 50 Consumer Organization',
  '666': 'PepsiCo Australia &amp; New Zealand',
  '668': 'KKR Capstone',
  '683': 'Multibillion-dollar Media/Internet Service Provider Company',
  '684': 'Multibillion-dollar Internet/Media Company',
  '685': 'High-Growth Inc. 500 Consumer Goods Company',
  '688': 'Fortune 400 Technology Company',
  '691': 'Multibillion-dollar Energy Retailer',
  '692': 'Compass',
  '713': 'Vista Consulting Group',
  '716': 'CompuCom',
  '717': 'QBE Insurance',
  '720': 'Cigna',
  '721': 'Silver Lake Partners',
  '724': 'Multibillion-Dollar Financial Services Company',
  '728': 'Ross Stores, Inc.',
  '729': 'Private Equity-Backed Apparel Company',
  '733': 'The Gap, Inc.',
  '736': 'Fast-Growing Multibillion-dollar Distribution Company',
  '739': 'Charles Schwab',
  '740': 'Rocketmiles, a Priceline Group Company',
  '741': 'Multimillion-dollar Private Software Company',
  '744': 'Premier Growth-Oriented Private Equity Firm',
  '747': 'Gap Inc.',
  '749': 'Waste Management',
  '752': 'Non-Profit Organization',
  '753': 'aden + anais',
  '754': 'Multibillion-dollar Financial Services Company',
  '770': 'High-Growth Consumer Company',
  '772': 'Venture Capital-Backed Real Estate Technology Company',
  '774': 'Redbox',
  '775': 'Groupe SEB',
  '778': '$15 billion Consumer &amp; Consumer Healthcare Company',
  '779': 'Multibillion-dollar Technology Company',
  '784': 'Enterprise Software Company',
  '785': 'Senior Director',
  '786': 'People Development',
  '787': 'Biotechnology',
  '788': 'Biotechnology Company',
  '795': 'Biopharmaceutical Firm',
  '796': 'Biopharmaceutical Company',
  '797': 'High-Growth Biopharmaceutical Company',
  '799': 'Chemical Manufacturing Company',
  '801': 'TTI Floor Care North America',
  '803': 'Pure Barre',
  '805': 'Intuit',
  '807': 'US Foods',
  '809': 'Whirlpool Corporation',
  '810': 'Private Equity-Owned Higher Education Company',
  '818': 'Dynamic Company',
  '821': 'Loyalty Solutions Company',
  '822': 'Multi-billion dollar Consumer Product Manufacturer',
  '824': 'Capital Group',
  '827': 'Environment Services Provider',
  '843': 'Sailthru',
  '845': 'DigitasLBi',
  '848': 'High-growth Technology Company',
  '856': 'Hickory Farms, Inc.',
  '865': 'High-growth Consumer Goods Company' };

export const industries = { '25': 'Manufacturing',
  '26': 'Services',
  '42': 'Investment Management',
  '45': 'Technology',
  '50': 'Private Equity',
  '67': 'Nonprofit',
  '162': 'Consumer Goods',
  '170': 'Automotive',
  '225': 'Entertainment',
  '231': 'Retail',
  '234': 'Financial Services',
  '242': 'Healthcare',
  '651': 'Real Estate',
  '653': 'Startup',
  '846': 'Advertising' };

export const titles = { '6': 'Associate',
  '7': 'Director',
  '15': 'Consultant',
  '16': 'Manager',
  '17': 'Officer',
  '18': 'Partner',
  '19': 'Principal',
  '22': 'Strategy',
  '23': 'Finance',
  '24': 'Operations',
  '31': 'Senior Director',
  '32': 'Senior Director',
  '34': 'Strategy',
  '37': 'Pricing',
  '39': 'Pricing',
  '41': 'Co-Founder',
  '51': 'Operations Executive',
  '54': 'Vice President, FP&amp;A',
  '60': 'Senior Vice President',
  '63': 'Head of U.S. Operations',
  '69': 'Group Managing Director',
  '72': 'Product Management',
  '79': 'Strategy &amp; Marketing',
  '80': 'Lead Account Director',
  '83': 'Chief Technology Officer',
  '85': 'Strategic Planning',
  '87': 'Chief Operating Officer',
  '95': 'Head of Client Marketing',
  '106': 'Managing Director',
  '108': 'Strategy &amp; Business Development',
  '111': 'Planning',
  '118': 'Direct Sourcing Leader',
  '124': 'Strategy',
  '125': 'Procurement Lead',
  '128': 'Infrastructure Operations',
  '130': 'Senior Operating Executive',
  '131': 'Chief Procurement Officer',
  '134': 'Strategy Lead',
  '142': 'M&amp;A',
  '149': 'General Manager',
  '158': 'Business Unit President',
  '160': 'Executive Director, North America Strategy*',
  '161': 'North American Strategy',
  '169': 'Group Strategy and Business Development Director',
  '172': 'Director',
  '174': 'Analyst',
  '175': 'Director of Corporate Strategy &amp; Development',
  '185': 'Director of Corporate Strategy',
  '187': 'Director of Strategy',
  '195': 'SVP, Operations',
  '199': 'Director of Financial Planning',
  '201': 'Vice President, Strategy',
  '202': 'Vice President, Product Dev., BD, and Operations',
  '203': 'Director, Corporate Strategy &amp; Development',
  '204': 'Vice President, Online Marketing &amp; Product Strategy',
  '205': 'Vice President, Strategic Planning',
  '206': 'Director, Product Management - Mobile Security',
  '207': 'Director, Product Management - Backup',
  '208': 'Senior Director, Strategy',
  '209': 'Vice President, Strategy &amp; Marketing',
  '210': 'Director, Corporate Strategy',
  '211': 'Director, Consumer Strategy',
  '212': 'Director, Strategy',
  '213': 'Director, Corporate Planning &amp; Strategy',
  '214': 'SVP, Strategy &amp; Business Development',
  '215': 'SVP, Strategic Planning &amp; Business Development',
  '216': 'Vice President, Strategy &amp; Business Development',
  '217': 'Director, Business Development',
  '218': 'Senior Director, Client Marketing',
  '219': 'Vice President, Pricing',
  '220': 'Vice President, Infrastructure Operations',
  '221': 'Director, M&amp;A',
  '222': 'Senior Director, M&amp;A',
  '223': 'Director, Financial Planning',
  '224': 'Vice President, FP&amp;A',
  '228': 'Vice President, Handling Operations',
  '230': 'Director, Consumer Electronics',
  '233': 'Senior Vice President, Consumer Co-brands',
  '241': 'Vice President, Corporate Strategy',
  '243': 'Senior Vice President',
  '244': 'Operations',
  '246': 'Senior Vice President, Operations',
  '247': 'Director, Global Strategy',
  '249': 'Vice President, Merchandising',
  '252': 'Director, Product Management',
  '253': 'Founder',
  '254': 'Founder, Partner',
  '256': 'Vice President, Product Development',
  '258': 'Director, Pricing',
  '259': 'Vice President, Retail Merchandising',
  '260': 'Manager, Corporate Strategy',
  '262': 'Director, Strategic Development',
  '265': 'Vice President &amp; CFO',
  '266': 'Vice President &amp; CFO',
  '285': 'Vice President &amp; Head of Client Marketing',
  '286': 'Head of Consumer Engagement Strategy',
  '288': 'Talent Acquisition',
  '289': 'Vice President',
  '290': 'Talent Acquisition',
  '291': 'Vice President, Talent Acquisition',
  '296': 'President, Learner Response Systems and Assessment*',
  '297': 'Senior Vice President*',
  '299': 'Chief Technology Officer*',
  '300': 'Director, Strategy &amp; Development',
  '301': 'Category Leader',
  '308': 'Senior Director, Product Management &amp; Marketing',
  '310': 'Multi-Million Dollar Private Software Company',
  '316': 'Franchise President',
  '319': 'Director, Enterprise Strategy Development',
  '321': 'Vice President, Enterprise Strategy Development',
  '324': 'Senior Vice President, Operations*',
  '332': 'Operating Executive',
  '592': 'Chief Marketing Officer',
  '593': 'International',
  '594': 'Chief Marketing Officer, International',
  '596': 'Chief Operations Officer',
  '599': 'Head of Global Strategic Pricing',
  '600': 'Corporate Development and Business Services',
  '604': 'Corporate Development &amp; Business Services*',
  '605': 'COO',
  '606': 'Corporate Development',
  '607': 'VP',
  '608': 'Vice President Corporate Development',
  '609': 'Vice President Corporate Development and Business Services*',
  '614': 'Chief of Staff to Founder &amp; CEO',
  '616': 'Vice President &amp; Head of Global Strategic Pricing',
  '617': 'VP, Made up stuff etc. *',
  '618': 'VP, Business Development &amp; Operations',
  '619': 'Vice President, Corporate Development and Business Services',
  '621': 'Business Dev. &amp; Partner Products',
  '622': 'Vice President, Business Dev. &amp; Channel Sales',
  '625': 'President and General Manager',
  '626': 'EVP, CFO &amp; Chief Strategy Officer',
  '629': 'Senior Associate',
  '630': 'Principal, Operating Group',
  '632': 'Director, Information Technology',
  '633': 'Senior Director, Pricing',
  '635': 'Vice President, Retail Merchandising',
  '637': 'Senior Manager, Corporate Strategy',
  '638': 'Divisional Vice President, Strategic Sourcing',
  '639': 'Indirect Procurement Principal',
  '640': 'Director, Business Transformation &amp; Globalisation Strategy',
  '643': 'Senior Vice President, Corporate Development &amp; Strategy',
  '646': 'Chief Strategy Officer',
  '648': 'Continuous Improvement',
  '649': 'Vice President, Continuous Improvement',
  '652': 'COO / CFO',
  '654': 'Business Intelligence',
  '655': 'Director, Business Intelligence',
  '656': 'Director, Channel Strategy &amp; Management',
  '657': 'Director, Product Development',
  '658': 'Vice President, Operations',
  '660': 'Founder &amp; CEO',
  '663': 'Vice President, eCommerce',
  '665': 'Chief Financial Officer',
  '667': 'CFO',
  '681': 'Financial Planning &amp; Analysis',
  '682': 'Senior Vice President, Financial Planning &amp; Analysis',
  '686': 'Principal Product Manager, Targeted Attack',
  '687': 'Multi-Billion Dollar Technology Company',
  '689': 'Principal Product Manager',
  '690': 'Vice President, Head',
  '693': 'Director, Technology Operating Lead',
  '694': 'Head of Marketing Excellence',
  '712': 'President, Over the Counter',
  '714': 'Vice President, Strategy &amp; Corporate Development',
  '715': 'President, End-User Enablement',
  '718': 'Global Head of Procurement',
  '719': 'Vice President, Enterprise Product Solutions',
  '722': 'Director, Corporate &amp; Investment Banking Consulting',
  '723': 'Vice President, Corporate &amp; Investment Banking Consulting',
  '725': 'Vice President, Head of Commercial',
  '726': 'Managing Director, UK',
  '727': 'Senior Vice President, Strategy &amp; Marketing',
  '730': 'UK Managing Director',
  '731': 'Multibillion-Dollar Business Unit',
  '732': 'President, Multibillion-Dollar Business Unit',
  '734': 'Executive Director, Global Strategy',
  '735': 'Vice President, Chief Human Resources Officer',
  '737': 'Vice President, Supply Chain &amp; Logistics-Global',
  '738': 'Senior Vice President, Client Experience',
  '742': 'DVP, Inventory Management',
  '743': 'Director, Operating Group',
  '745': 'Logistics Strategy',
  '746': 'Senior Director, Logistics Strategy',
  '748': 'Vice President, Revenue Management',
  '750': 'Vice President, Revenue Management',
  '751': 'Chief Executive Officer',
  '756': 'Senior Manager, Strategy',
  '757': 'Senior Manager, Strategy',
  '758': 'President',
  '759': 'Vice President',
  '765': 'Specialist Insurer',
  '769': 'Vice President, Human Resources',
  '771': 'Regional General Manager',
  '773': 'Senior Vice President, Operations &amp; Merchandising',
  '776': 'Digital Acceleration Officer',
  '777': 'Vice President, Global Professional Marketing &amp; Sales',
  '780': 'Senior Director, Product Management',
  '781': 'Group Vice President, Strategy',
  '783': 'Group Vice President',
  '789': 'People Development',
  '790': 'People &amp; Development',
  '791': 'Senior Director',
  '792': 'People &amp; Development',
  '793': 'Senior Director, People &amp; Development',
  '794': 'Director, People &amp; Organizational Development',
  '798': 'Director, Strategic Development',
  '800': 'Chief Marketing Officer, North America',
  '804': 'Chief Information Security Officer',
  '806': 'Executive Vice President, Strategy &amp; Revenue Management',
  '808': 'Global Vice President, Product Development Excellence',
  '811': 'People &amp; Organizational Development',
  '812': 'R&amp;D',
  '813': 'Senior Director, People &amp; Organizational Development, R&amp;D',
  '817': 'Executive',
  '819': 'Vice President, Global Strategy &amp; Business Development',
  '820': 'Group Vice President of Account Management',
  '823': 'SVP, Head of Strategy &amp; Innovation',
  '826': 'Chief of Staff',
  '842': 'Senior Director, Corporate Strategy',
  '844': 'SVP, Head of Operations, North America',
  '847': 'Vice President, Business Intelligence &amp; Data Strategy',
  '863': 'Head of Product Marketing',
  '864': 'Head of Retail Operations' };

export const trackTypes = { '21': 'General Management',
  '237': 'Marketing',
  '293': 'Human Resources',
  '760': 'Strategy',
  '761': 'Finance',
  '762': 'Operations',
  '764': 'Technology' }

// http://www.consultanttrack.com/wp-json/wp/v2/track-types/?per_page=100
// var firms = {};
// arr.forEach((firm) => {
// 	firms[firm.id] = firm.name
// })
// console.log(firms)